# main.py

import os
import random
from datetime import datetime
from scripts.generate_script import generate_prompt
from scripts.text_to_speech import make_voice
from scripts.create_video import create_video
from scripts.upload import upload_video

def run_bot():
    print("🎯 STARTING AI VIDEO BOT PROCESS")

    today_str = datetime.now().strftime("%Y-%m-%d")

    # STEP 1: Generate unique prompt
    print("🧠 Generating video prompt using Gemini...")
    prompt_text = generate_prompt()

    if not prompt_text:
        print("❌ Prompt was empty. Stopping.")
        return

    print("✅ Prompt:", prompt_text)

    # STEP 2 (optional): Generate TTS audio
    print("🎙️ Generating TTS voice")
    audio_path = make_voice(prompt_text)

    if not audio_path or not os.path.isfile(audio_path):
        print("❌ Audio creation failed.")
        return

    print("✅ Audio created:", audio_path)

    # STEP 3: Create video
    print("🎞️ Generating vertical video with FFmpeg...")
    try:
        output_video_path = create_video(audio_path)
    except Exception as e:
        print("❌ Video creation failed:", e)
        return

    print("✅ Final video created:", output_video_path)

    # Final video title + description
    video_title = f"Satisfying Short – {today_str}"
    video_description = f"""Daily relaxing content generated by AI 🤖

Prompt: {prompt_text}

#Shorts #Satisfying #Relaxing #OddlySatisfying
"""

    # STEP 4: Upload to YouTube
    print("📤 Uploading to YouTube...")
    try:
        upload_video(output_video_path, video_title, video_description)
        print("🎉 Upload successful!")
    except Exception as e:
        print("❌ Upload failed:", e)

if __name__ == "__main__":
    run_bot()